"use client";
import React, { useEffect } from "react";
import { Mixpanel } from "../mixpanel";
export default function page() {
  useEffect(() => {
    Mixpanel.track("Page Loaded");
    Mixpanel.track_links("a", "Clicked Link");
  }, []);
  const handleButtonClick = () => {
    Mixpanel.track("Button clicked");
    alert("Button clicked!");
  };

  return (
    <>
      {/* // banner website created by create next app */}
      <div className="banner">
        <div className="container">
          <h1>Create Next App</h1>
          <p>Generated by create next app</p>
        </div>
      </div>
      {/* // main content */}
      <div className="container">
        <h2>Getting Started</h2>
        <p>
          Edit <code>pages/index.js</code> and save to reload.
        </p>
        <p>
          <a href="#">
            <button onClick={handleButtonClick} className="button__more">
              Learn More
            </button>
          </a>
        </p>
      </div>
      {/* // footer */}
      <div className="footer">
        <div className="container">
          <p>
            <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              Powered by Vercel
            </a>
          </p>
        </div>
      </div>
    </>
  );
}
